version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hisabkitab-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: hisabkitab-frontend
    ports:
      - "5173:80" # Nginx serves frontend on container port 80 → EC2 5173
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge